name: Scrape Inciweb incident data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "4,24,44 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Fetch latest data
        run: |-
          curl https://inciweb.nwcg.gov/feeds/json/esri/ | jq '.'  > incidents.json
      - name: Commit and push if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
